# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MappingTools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(max_length=256, null=True)),
                ('software_link', models.URLField(max_length=256, null=True)),
                ('data_input_format', models.CharField(max_length=256, null=True)),
                ('data_output_format', models.CharField(max_length=256, null=True)),
                ('is_penn_subscription', models.NullBooleanField()),
                ('cost_penn', models.CharField(max_length=256, null=True)),
                ('cost_non_penn', models.CharField(max_length=256, null=True)),
                ('penn_research_guides', models.URLField(max_length=256, null=True)),
                ('other_research_guides', models.URLField(max_length=256, null=True)),
                ('notes', models.CharField(max_length=256, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tools.MappingTools')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_text', models.CharField(max_length=200)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tools.UserStories')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.Project')),
                ('recommendation', mptt.fields.TreeManyToManyField(blank=True, null=True, to='tools.MappingTools')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
