# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_remove_mappingtools_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappingtools',
            name='level',
        ),
        migrations.RemoveField(
            model_name='mappingtools',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='mappingtools',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='mappingtools',
            name='tree_id',
        ),
    ]
