# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 18:27
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_auto_20170515_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingtools',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tools.MappingTools'),
        ),
    ]
