# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_mappingtools_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappingtools',
            name='level',
        ),
        migrations.RemoveField(
            model_name='mappingtools',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='mappingtools',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='mappingtools',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='mappingtools',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='userstories',
            name='recommendation',
            field=models.ManyToManyField(blank=True, null=True, to='tools.MappingTools'),
        ),
    ]
