# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_auto_20170515_1840'),
    ]

    operations = [
	migrations.RenameModel('Project', 'Inquiry')
    ]
