# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_auto_20170602_1351'),
    ]

    operations = [
	migrations.RenameField('UserStories', 'project', 'inquiry')
    ]
