# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_auto_20170602_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=50)),
                ('page_number', models.IntegerField(default=1)),
                ('off_ramp_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name_plural': 'inquiries'},
        ),
        migrations.AlterModelOptions(
            name='mappingtools',
            options={'verbose_name_plural': 'mapping tools'},
        ),
        migrations.AlterModelOptions(
            name='userstories',
            options={'verbose_name_plural': 'user stories'},
        ),
        migrations.AddField(
            model_name='page',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.Inquiry'),
        ),
    ]
