# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_userstories_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstories',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tools.Page'),
        ),
    ]
